'preprocessing':
#  '1':
#  - phase_shift
#  - {}
  '1':
  - bandpass_filter
  - freq_min: 300
    freq_max: 6000
  '2':
  - common_reference
  - operator: median
    reference: global

'sorting':
  'kilosort2':
    'car': False     # common average referencing
    'freq_min': 150  # highpass filter cutoff, False nor 0 does not work to turn off. (results in KS error)
  'kilosort2_5':
    'car': False
    'freq_min': 150
  'kilosort3':
    'car': False
    'freq_min': 300
