'preprocessing':
  '1':
  - correct_motion
  - {}
  '2':
  - whiten
  - dtype: float32
  '3':
  - zscore
  - chunk_size: 50
  '4':
  - depth_order
  - channel_ids:
    - 'imec0.ap#AP3'
#  '5':
#  - resample
#  - resample_rate: 1  # TODO: why does resample rate 2 not work?
#    margin_ms: 50
